name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Get code to get access to custom our actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node_version }}

      - name: Lint
        run: yarn run lint

      - name: Build TypeScript
        run: yarn run build

      - name: Run tests
        run: yarn run test

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Get code to get access to custom our actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/setup

      - name: Release
        run: |
          yarn build
          yarn semantic-release
